modLoader="javafml" 
loaderVersion="[39,)"
license="custom"
issueTrackerURL="https://github.com/Sniffity/Panthalassa/issues"

[[mods]]
modId="panthalassa"
version="${file.jarVersion}"
displayName="Panthalassa Mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/panthalassa"
#logoFile="examplemod.png" #optional
authors="Sniffity"
description="Panthalassa is a mod for Minecraft 1.18.1 that adds prehistoric aquatic life to your world!"

[[dependencies.panthalassa]] #optional
    modId="forge"
    mandatory=true
    versionRange="[39.0.0,)"

[[dependencies.panthalssa]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,)"

