modLoader="javafml" 
loaderVersion="[39,)"
license="custom"
issueTrackerURL="https://github.com/Sniffity/Panthalassa/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/panthalassa"
logoFile="panthalassa.png"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="geckolib3"
    mandatory=true
    versionRange="[3.0.11,)"
    ordering="BEFORE"
    side="BOTH"